### ISSUE TITLE
Add your projects !! 

### ISSUE THREAD

**Issue by Niraj-1729** [Niraj-1729/Hacktoberfest#11]
I'll be accepting relevant projects under this!!

**Comment by AdityaDhavale** [comment]
@Niraj-1729 I would like to work on it . PLease assign me

**Comment by Niraj-1729** [comment]
> @Niraj-1729 I would like to work on it . PLease assign me

your contribution will be appreciated !!

**Comment by AdityaDhavale** [comment]
@Niraj-1729 I've added my project . Please check and kindly merge my PR.

**Comment by Niraj-1729** [comment]
> @Niraj-1729 I've added my project . Please check and kindly merge my PR.

Add your project in separate folder and organise it properly

**Comment by AdityaDhavale** [comment]
@Niraj-1729 I've created a separate folder named My_Project and added all files of my project in that. Please check and kindly merge my PR.

**Comment by sarthaks55** [comment]
hello @Niraj-1729 , I would like to add my advice generator website to the front-end project collection as a part of hacktoberfest event.

**Comment by Niraj-1729** [comment]
Yes but make sure to add in a separate folder and don't forget to giva a star to this repo
