### ISSUE TITLE
give space between subscribe box and trending topics section 

### ISSUE THREAD

**Issue by Niraj-1729** [Niraj-1729/Hacktoberfest#2]
![2023-10-12 (1)](https://github.com/Niraj-1729/Hacktoberfest/assets/98650481/e1c66192-01ca-4277-9857-4949a448ae01)

**Comment by sumit-022** [comment]
Can I do it?

**Comment by Niraj-1729** [comment]
I assigned this to @sumit-022

**Comment by sumit-022** [comment]
If you want I can convert your website into react and improve it a lot better

**Comment by Niraj-1729** [comment]
> If you want I can convert your website into react and improve it a lot better

sure go for it

**Comment by 0silverback0** [comment]
which site is this ? if i can do it I'll do it if not already completed
