### ISSUE TITLE
[Bug] Customizing the UI/UX of landing page 

### ISSUE THREAD

**Issue by Tushar1323** [Niraj-1729/Hacktoberfest#24]
Creating a UI/UX of front page with customize the Header and body .

**Comment by Niraj-1729** [comment]
sure @Tushar1323 go for it, your contribution will be highly appreciated
Don't forget to star this repo for better reach !!

**Comment by Tushar1323** [comment]
I suggest you to add a live link of this repo. in about section .
So that everyone can easily see the upgradation .
