### ISSUE TITLE
Work on responsiveness of gym website 

### ISSUE THREAD

**Issue by Niraj-1729** [Niraj-1729/Hacktoberfest#25]

**Comment by sid172014** [comment]
@Niraj-1729 Hey there , I hope you’re doing good , can you please assign this issue to me ?

**Comment by Niraj-1729** [comment]
I assigned this to @sid172014 
yes sure go for it !!
give a star for better reach 🌟

**Comment by sid172014** [comment]
Hey @Niraj-1729 i've created the pull request #34  for this issue , can you please take a look ...
